sudo: required
services:
  - docker

language: go

go:
  - tip

notifications:
  email: false

install:
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - CGO_ENABLED=0 GOOS=linux go build
  - docker build -t "$DOCKER_USER"/go-ssl-redirect:latest .

deploy:
  provider: script
  script: ./docker-deploy.sh
  on:
    branch: master
